name: my-snap-name
summary: Single-line elevator pitch for your amazing snap under 79 chars.
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

# Just for humans, typically '1.2+git' or '1.3.2'
# The wrapping single quotes are often required to avoid the version string
# being accidentally interpreted as a YAML floating point number(like '1.2').
# http://yaml.org/spec/1.2/spec.html#id2804092
# https://arp242.net/weblog/yaml_probably_not_so_great_after_all.html#surprising-behaviour
version: determined-by-version-script

# (OPTIONAL) The version string can also be dynamically determined via scriping
# , in this case the value of the `version` key will be ignored (but the key is
# still required).
# version-string: snap/utilites/set-snap-version.bash
version-script: |
  set \
    -o errexit \
    -o nounset

  upstream_version="$(
    git \
      -C parts/my-app-part/src \
      describe \
      --always \
      --dirty=-d \
      --tags \
    | sed s/^v//
  )"

  packaging_revision="$(
    git \
      describe \
      --abbrev=4 \
      --always \
      --dirty=-d
  )"

  printf -- '%s' "${upstream_version}+pkg-${packaging_revision}"

confinement: devmode # use 'strict' once you have the right plugs and slots
grade: devel
icon: snap/gui/icon.png

apps:
  my-app:
    command: my-app
    desktop: share/applications/my-app.desktop
    #plugs:
    #- desktop
    #- desktop-legacy
    #- x11
    #- unity7
    #- wayland

    #slots:

parts:
  # Launchers to fix the runtime environment to make the snap works
  launchers:
    source: snap/launchers
    source-type: local
    plugin: dump

    override-build: |
      set -eu

      mkdir \
        --parents \
        "$SNAPCRAFT_PART_INSTALL"/bin
      cp \
        --force \
        --verbose \
        *-launch \
        "$SNAPCRAFT_PART_INSTALL"/bin \
        || true # Allow shipping no launchers

  # Patches to make the snap working if it can't be solved via launchers
  patches:
    source: snap/patches
    source-type: local
    plugin: dump

    # DISABLED: Bug #1775582 “`organize:{ /: another-dir/ }` causes the items under host root directory to be copied in another-dir” : Bugs : Snapcraft
    # https://forum.snapcraft.io/t/organize-another-dir-causes-the-items-under-host-root-directory-to-be-copied-in-another-dir/5806
    #organize:
        #/: patches/
    override-build: |
      set -eu

      snapcraftctl build

      mkdir \
        --parents \
        "$SNAPCRAFT_PART_INSTALL"/patches
      mv \
        "$SNAPCRAFT_PART_INSTALL"/*.diff \
        "$SNAPCRAFT_PART_INSTALL"/*.patch \
        "$SNAPCRAFT_PART_INSTALL"/*.sed \
        "$SNAPCRAFT_PART_INSTALL"/patches \
        || true # Empty patches folder is allowed
    stage:
    - patches/*
    override-prime: 'true'

  # Helper programs to aid in certain part of snap building, like a install program for a certain part
  utilities:
    source: snap/utilities
    override-pull: |
      set -eu

      snapcraftctl pull

      mkdir \
        --parents \
        utilities
      mv \
        *.bash \
        utilities \
        || true # It is OK if nothing is in the directory

    plugin: dump
    override-prime: 'true'

  my-app:
    after:
    - patches

    # See 'snapcraft plugins'
    plugin: nil

    override-stage: |
      set -eu

      snapcraftctl stage

      sed \
        --file "${SNAPCRAFT_STAGE}"/patches/patch-desktop-entries.sed \
        --in-place \
        "${SNAPCRAFT_STAGE}"/share/applications/*.desktop
